/**
 * @readonly
 * @enum
 */
const ERROR_CODE = {
  AUTHERR: 'AUTHORIZATION_ERROR',
  NOAUTHERR: 'MISSING_AUTHORIZATION',
  INVLDAUTHTOKEN: 'INVALID_AUTH_TOKEN',
  INACTIVEACCT: 'INACTIVE_ACCOUNT',
  EXPIREDTOKEN: 'EXPIRED_TOKEN',
  INVLDREQ: 'INVALID_REQUEST',
  PERMERR: 'PERMISSION_ERROR',
  LIMITERR: 'LIMIT_ERROR',
  FEEERR: 'FEE_ERROR',
  NOTFOUND: 'RESOURCE_NOT_FOUND',
  APPERR: 'APPLICATION_ERROR',
  HTTPREQERR: 'INTERNAL_REQ_ERROR',
  DUPLRCRD: 'DUPLICATE_RECORD',
  VALIDATIONERR: 'VALIDATION_ERROR',
  INVLDDATA: 'INVALID_REQUEST_DATA',
  RTLIMERR: 'RATE_LIMIT_ERROR',
  // Creator Card Errors
  SL02: 'SL02',
  AC01: 'AC01',
  AC05: 'AC05',
  NF01: 'NF01',
  NF02: 'NF02',
  AC03: 'AC03',
  AC04: 'AC04',
};

const ERROR_STATUS_CODE_MAPPING = {
  AUTHORIZATION_ERROR: 401,
  MISSING_AUTHORIZATION: 401,
  INVALID_AUTH_TOKEN: 401,
  INACTIVE_ACCOUNT: 401,
  EXPIRED_TOKEN: 401,
  PERMISSION_ERROR: 401,
  INVALID_REQUEST: 403,
  LIMIT_ERROR: 403,
  FEE_ERROR: 403,
  RESOURCE_NOT_FOUND: 404,
  DUPLICATE_RECORD: 409,
  APPLICATION_ERROR: 500,
  RATE_LIMIT_ERROR: 429,
  // Creator Card Error Mappings
  SL02: 400,
  AC01: 400,
  AC05: 400,
  NF01: 404,
  NF02: 404,
  AC03: 403,
  AC04: 403,
};

module.exports = { ERROR_CODE, ERROR_STATUS_CODE_MAPPING };
